---
- name: add group "admin"
  group: 
    name: admin

- name: Allow 'admin' group to have passwordless sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%admin'
    line: '%admin ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'

- name: remove "90-cloud-init-users"
  file:
    state: absent
    path: /etc/sudoers.d/90-cloud-init-users

- name: add group "src"
  group: 
    name: src

- name: ensure "src" with right permissions
  file: 
    path: /usr/src/
    owner: root
    group: src
    state: directory
    recurse: yes
<<<<<<< HEAD
    mode: 0775

- name: Copy the configuration file
  template: 
    src: config
    dest: /etc/selinux/config
    owner: root
    group: root
 
- name: check if swap file exists
  stat: 
    path: /dev/xvde3
  register: swap_info
  
- name: Swap off xvde3
  command: "/sbin/swapoff /dev/xvde3"
  when: swap_info.stat.exists == true
  
=======
    mode: 0755

*- name: Copy the configuration file
  template: src=config.xml dest=/etc/selinux/config
  notify: restart selinux

- name: Swap off xvde3
  shell: "/sbin/swapoff /dev/xvde3"

>>>>>>> 35c7b3b4f6ff591be67c396d6845acc8b8a0f3c4
- name: Comment sda3 in fstab file
  replace:
    path: /etc/fstab
    regexp: '(.*/dev/sda3.*)'
    replace: '#\1'

<<<<<<< HEAD
- name: ensure "modprobe" with right permissions
  file:
    path: /etc/modprobe.d/modprobe.conf
    owner: root
    group: root
    state: touch
    mode: 0755

- name: Disable file systems you don't need
  command: echo "install {{ item }} /bin/true" >> /etc/modprobe.d/modprobe.conf
=======
- name: Ensure swap file doesn't exist (if configured).
  file:
    path: "{{ swap_file_path }}"
    state: absent

- name: Disable file systems you don't need
  shell: install "{{ item }}" /bin/true
>>>>>>> 35c7b3b4f6ff591be67c396d6845acc8b8a0f3c4
  with_items: 
    - cramfs
    - freexvfs
    - jffs2
    - hfs
    - hfsplus
    - squashfs
<<<<<<< HEAD
    - udf
=======
    - udf
>>>>>>> 35c7b3b4f6ff591be67c396d6845acc8b8a0f3c4
