---
- name: Create Compute Engine instances
  hosts: local
  gather_facts: False
  vars_files:
    - gce_vars/auth
    - gce_vars/machines
    - gce_vars/zone
  tasks:
    - name: Create an IP address for first instance
      gcp_compute_address:
        name: "{{ name_zonea }}-ip"
        region: "{{ region }}"
        project: "{{ project }}"
        service_account_file: "{{ credentials_file }}"
        auth_kind: "{{ auth_kind }}"
      register: gcea_ip
    - name: " a network facts"
      gcp_compute_network_facts:
        filters:
        - name = dev
        project: "{{ project }}"
        auth_kind: serviceaccount
        service_account_file: "{{ credentials_file }}"
      register: network
    - debug:
        msg: our network is {{ network.name }}
    - name: Bring up the first instance in the first zone.
      gcp_compute_instance:
        name: "{{ name_zonea }}"
        machine_type: "{{ machine_type }}"
        disks:
        - auto_delete: true
          boot: true
          initialize_params:
            source_image: "{{ image }}"
        network_interfaces:
        - network: "{{ network }}"
          access_configs:
          - name: External NAT
            nat_ip: "{{ gcea_ip }}"
            type: ONE_TO_ONE_NAT
        zone: "{{ zone }}"
        project: "{{ project }}"
        service_account_file: "{{ credentials_file }}"
        service_accounts:
          - email: 565146480958-compute@developer.gserviceaccount.com
        auth_kind: "{{ auth_kind }}"
      register: gcea
