---
# compute-video-demo-ansible
- name: Create Compute Engine instances
  hosts: local
  gather_facts: False
  vars_files:
    - gce_vars/auth
    - gce_vars/machines
    - gce_vars/zone
  tasks:
    - name: Create an IP address for first instance
      gcp_compute_address:
        name: "{{ name_zonea }}-ip"
        region: "{{ region }}"
        project: "{{ project }}"
        service_account_file: "{{ credentials_file }}"
        auth_kind: "{{ auth_kind }}"
      register: gcea_ip

    - name: Create a first instance
      gce:
        instance_names: "{{ name_zonea }}"
        zone: us-central1-a
        machine_type: n1-standard-1
        state: present
        disk_auto_delete: true
        image: "{{ image }}"
        network: dev1
        subnetwork: dev1
        preemptible: false
        ip_forward: true
        service_account_permissions:
          - storage-full
          - taskqueue
          - https://www.googleapis.com/auth/ndev.clouddns.readwrite
        #service_account_email: "{{ service_mail }}"
        #credentials_file: "{{ credentials_file }}" 
        project_id: "{{ project }}"
      register: gcea
