- name: Compute Engine Instance Examples
  hosts: localhost
  vars:
      service_account_email: "565146480958-compute@developer.gserviceaccount.com"
      credentials_file: "~/serviceaccounts/anilgcp.json"
      zone: "us-central1-a"
      region: "us-central1"
      project_id: "myproject-255706"
  tasks:
    - name: create multiple instances
      # Basic provisioning example.  Create multiple Debian 8 instances in the
      # us-central1-a Zone of n1-standard-1 machine type.
      gce:
        instance_names: test1,test2,test3
        zone: us-central1-a
        machine_type: n1-standard-1
        image: centos-7-v20190619
        state: present
        service_account_email: "{{ service_account_email }}"
        credentials_file: "{{ credentials_file }}"
        project_id: "{{ project_id }}"
        metadata : '{ "startup-script" : "yum update" }'
      register: gce

    - name: Save host data
      add_host:
        hostname: "{{ item.public_ip }}"
        groupname: gce_instances_ips
      with_items: "{{ gce.instance_data }}"

    - name: Wait for SSH for instances
      wait_for:
        delay: 1
        host: "{{ item.public_ip }}"
        port: 22
        state: started
        timeout: 30
      with_items: "{{ gce.instance_data }}"

- name: Configure Hosts
  hosts: gce_instances_ips
  become: yes
  become_method: sudo
  roles:
    - redis
