- name: Create an instance
  hosts: localhost
  gather_facts: no
  
  vars:
      gcp_project: myproject-255706
      gcp_cred_kind: serviceaccount
      gcp_cred_file: ~/serviceaccounts/anilgcp.json
      zone: "us-central1-a"
      region: "us-central1"

  tasks:
   - name: create a disk
     gcp_compute_disk:
         name: 'disk-instance'
         size_gb: 10
         source_image: 'projects/centos-cloud/global/images/centos-7-v20190619'
         zone: "{{ zone }}"
         project: "{{ gcp_project }}"
         auth_kind: "{{ gcp_cred_kind }}"
         service_account_file: "{{ gcp_cred_file }}"
         scopes:
           - https://www.googleapis.com/auth/compute
         state: present
     register: disk
   
   - name: create a network
     gcp_compute_network:
         name: 'dev1'
         project: "{{ gcp_project }}"
         auth_kind: "{{ gcp_cred_kind }}"
         service_account_file: "{{ gcp_cred_file }}"
         scopes:
           - https://www.googleapis.com/auth/compute
         state: present
     register: network
   - name: create a address
     gcp_compute_address:
         name: 'address-instance'
         region: "{{ region }}"
         project: "{{ gcp_project }}"
         auth_kind: "{{ gcp_cred_kind }}"
         service_account_file: "{{ gcp_cred_file }}"
         scopes:
           - https://www.googleapis.com/auth/compute
         state: present
     register: address
   - name: create a instance
     gcp_compute_instance:
         state: present
         name: test-vm
         machine_type: n1-standard-1
         disks:
           - auto_delete: true
             boot: true
             source: "{{ disk }}"
         metadata:
             ssh-keys: nisum:ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDW2hqUKA9eVTFoNLQUlsOLXM0/9kiarANvhqA0fD8Zcvr1AH/MDirow+oJcIGibdtaPxfA66ukHsdOa3MKgft7eGSeZGeCcASQK8MSRPS5ZGXsFPImi/XFpZ8bId7ebKRhEEMrWFC3Qh/AwviRbKpqbvBxg/4DC2+J9+RPyRNlgx+LbUAP6F+WHt7XgGVMAhIY9X51hnkCU5ueKL3iT0j82jXVxzjKjpOIG/9O5aLSyPgDU/N2JxyA48A5q7lneKQJNL7mQF+0w0KbIko4dPYMAPAEhKqgI1zzzDDb7shcexGJqrotO4+KLkqYzrG+DojNZDoV36pvwCZdRORqdP6X nisum@DESKTOP-64O0AD7
         network_interfaces:
             - network: "{{ network }}"
               access_configs:
                 - name: 'External NAT'
                   nat_ip: "{{ address }}"
                   type: 'ONE_TO_ONE_NAT'
         zone: "{{ zone }}"
         project: "{{ gcp_project }}"
         auth_kind: "{{ gcp_cred_kind }}"
         service_account_file: "{{ gcp_cred_file }}"
         service_accounts:
           - email: 565146480958-compute@developer.gserviceaccount.com
         scopes:
           - https://www.googleapis.com/auth/compute
           - https://www.googleapis.com/auth/devstorage.read_only
     #     - storage-full
      #    - taskqueue
           - https://www.googleapis.com/auth/ndev.clouddns.readwrite 
     register: instance

   - name: Wait for SSH to come up
     wait_for: host={{ address.address }} port=22 delay=10 timeout=60

   - name: Add host to groupname
     add_host: hostname={{ address.address }} groupname=new_instances
  
   - name: Set authorized key took from file
     authorized_key:
         user: root
         state: present
         key: "{{ lookup('file', '/home/nisum/.ssh/id_rsa.pub') }}"
     delegate_to: "{{ address.address }}"

- name: Manage new instances
  hosts: new_instances
  connection: ssh
  sudo: True
  roles:
    - redis
