- name: Create an instance
  hosts: localhost
  gather_facts: no
  vars_files:
    - gce_vars/auth
    - gce_vars/machines
    - gce_vars/zone 

  tasks:
   - name: create a disk
     gcp_compute_disk:
         name: 'disk-{{ item }}'
         size_gb: 10
         source_image: '{{ image }}'
         zone: "{{ zone }}"
         project: "{{ gcp_project }}"
         auth_kind: "{{ gcp_cred_kind }}"
         service_account_file: "{{ gcp_cred_file }}"
         scopes:
           - https://www.googleapis.com/auth/compute
         state: present
     with_items: "{{ machines }}"
     register: disk

   - debug:
       var: disk

   - name: create a network
     gcp_compute_network:
         name: 'dev1'
         project: "{{ gcp_project }}"
         auth_kind: "{{ gcp_cred_kind }}"
         service_account_file: "{{ gcp_cred_file }}"
         scopes:
           - https://www.googleapis.com/auth/compute
         state: present
     register: network

   - name: create a address
     gcp_compute_address:
         name: 'addr-redis1'
         region: "{{ region }}"
         project: "{{ gcp_project }}"
         auth_kind: "{{ gcp_cred_kind }}"
         service_account_file: "{{ gcp_cred_file }}"
         scopes:
           - https://www.googleapis.com/auth/compute
         state: present
     register: addr

   - debug:
       var: addr

   - name: create a instance
     gcp_compute_instance:
         state: present
         name: "test-{{ item }}"
         machine_type: n1-standard-1
         disks:
           - auto_delete: true
             boot: true
             source: "{{ disk }}"
             initialize_params:
               disk_name: "disk-{{ item }}"
               source_image: "{{ image }}"
               disk_size_gb: 10
         metadata:
             ssh-keys: "{{ ssh_key }}"
         network_interfaces:
           - network:
               selfLink: "projects/{{ gcp_project }}/global/networks/dev"
             subnetwork:
               selfLink: "projects/{{ gcp_project }}/regions/{{ region }}/subnetworks/dev"
         zone: "{{ zone }}"
         project: "{{ gcp_project }}"
         auth_kind: "{{ gcp_cred_kind }}"
         service_account_file: "{{ gcp_cred_file }}"
         service_accounts:
           - email: "{{ service_mail }}"
         scopes:
           - https://www.googleapis.com/auth/compute
           - https://www.googleapis.com/auth/devstorage.read_only
           - https://www.googleapis.com/auth/ndev.clouddns.readwrite
     with_items: "{{ machines }}"
     register: gce_inst

   - debug:
       var: gce_inst

   - shell: gcloud compute instances add-access-config "test-{{ item }}" --zone "{{ zone }}" --access-config-name "External NAT" --address "{{ addr.address }}"
     run_once: true
     with_items: "{{ machines }}"

   - name: Wait for SSH to come up
     wait_for: host={{ addr.address }} port=22 delay=10 timeout=60

   - name: Add host to groupname
     add_host: hostname={{ addr.address }} groupname=new_instances
  
- name: Manage new instances
  hosts: new_instances
  connection: ssh
  sudo: True
  roles:
    - base_configuration
    - redis
