---
slave_output_buffer_limit: 1024m
maxmemory: 0
maxmemory_policy: volatile-lru
appendonly: 'yes'
auto_aof_rewrite_percentage: 100
auto_aof_rewrite_min_size: 64mb
service_port: 6767
service_name_list:
  - redis-lookout
  - redis-calculon-1
  - redis-radar-results-1
service_port_list:
  - 6400
  - 6380
  - 6392
